### ISSUE TITLE
TypeError: this.storage.read is not a function

### ISSUE THREAD

**Issue by florrain** [mokeddes/botbuilder-storage-redis#13]
Hi there,

Using the latest version available 1.0.9, I'm getting this error when the bot is trying to read/update its state. Any idea why could be causing this? Could it be the package is not compatible with recent versions of the botbuilder? I'm using botbuilder 4.8.0.

```
0|ms-bot  | TypeError: this.storage.read is not a function
0|ms-bot  |     at Promise.resolve.then (/var/www/ms-bot/releases/20200424210108/node_modules/botbuilder-core/lib/botState.js:63:37)
0|ms-bot  | Error: BotFrameworkAdapter.processActivity(): 500 ERROR
0|ms-bot  |  TypeError: this.storage.delete is not a function
0|ms-bot  |     at Promise.resolve.then (/var/www/ms-bot/releases/20200424210108/node_modules/botbuilder-core/lib/botState.js:141:91)
0|ms-bot  |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|ms-bot  |     at BotFrameworkAdapter.<anonymous> (/var/www/ms-bot/releases/20200424210108/node_modules/botbuilder/lib/botFrameworkAdapter.js:660:27)
0|ms-bot  |     at Generator.throw (<anonymous>)
0|ms-bot  |     at rejected (/var/www/ms-bot/releases/20200424210108/node_modules/botbuilder/lib/botFrameworkAdapter.js:12:65)
0|ms-bot  |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

I do have to say that the documentation in the readme does not match with the official sample applications: https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/45.state-management/index.js#L38

I'm passing an instance of the redisStorage directly to state objects:
```
const redisStateStorage = new RedisDbStorage(redisClient);
const conversationState = new ConversationState(redisStateStorage);
const userState = new UserState(redisStateStorage);
```

**Comment by florrain** [comment]
Nevermind that does not seem to be related to the package, closing 🔒
